# Generated by Django 3.0 on 2020-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fifth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fourth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sixth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
