# Generated by Django 3.0 on 2020-04-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200422_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifth',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='first',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fourth',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='second',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sixth',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='third',
            old_name='Title',
            new_name='title',
        ),
    ]
