# Generated by Django 3.0 on 2020-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20200422_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='any_message',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
