# Generated by Django 3.0 on 2020-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20200422_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
