# Generated by Django 3.0 on 2020-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20200422_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifth',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/fifth'),
        ),
        migrations.AlterField(
            model_name='fifth',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='first',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/first'),
        ),
        migrations.AlterField(
            model_name='fourth',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/fourth'),
        ),
        migrations.AlterField(
            model_name='fourth',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='second',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/second'),
        ),
        migrations.AlterField(
            model_name='second',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sixth',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/sixth'),
        ),
        migrations.AlterField(
            model_name='sixth',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='third',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/third'),
        ),
        migrations.AlterField(
            model_name='third',
            name='any_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
