# Generated by Django 3.0 on 2020-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20200423_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifth',
            name='File',
            field=models.FileField(default='', upload_to='media/fifth'),
        ),
        migrations.AlterField(
            model_name='first',
            name='File',
            field=models.FileField(default='', upload_to='media/first'),
        ),
        migrations.AlterField(
            model_name='fourth',
            name='File',
            field=models.FileField(default='', upload_to='media/fourth'),
        ),
        migrations.AlterField(
            model_name='second',
            name='File',
            field=models.FileField(default='', upload_to='media/second'),
        ),
        migrations.AlterField(
            model_name='sixth',
            name='File',
            field=models.FileField(default='', upload_to='media/sixth'),
        ),
        migrations.AlterField(
            model_name='third',
            name='File',
            field=models.FileField(default='', upload_to='media/third'),
        ),
    ]
