# Generated by Django 3.0 on 2020-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20200423_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='', max_length=100)),
                ('sem', models.IntegerField()),
                ('subject', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('any_message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('File', models.FileField(default='', upload_to='media/sixth')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fifth',
        ),
        migrations.DeleteModel(
            name='First',
        ),
        migrations.DeleteModel(
            name='Fourth',
        ),
        migrations.DeleteModel(
            name='Second',
        ),
        migrations.DeleteModel(
            name='Sixth',
        ),
        migrations.DeleteModel(
            name='Third',
        ),
    ]
